### ISSUE TITLE
[BUG] When Running Phables

### ISSUE THREAD

**Issue by MJNT1999** [Vini2/ds-bubbles#36] opened 2024-01-22 18:25 UTC
**Describe the bug**
Phables fails at Koverage step with error. I installed the latest version of phables using mamba, the install appears to work and the test is fine. The run fails when it reaches the coverage step. I have tried this with illumina files (shown below) and with an ONT from an isolate which was assembled with Flye. Any insight into this would be very much appreciated!

**To Reproduce**

```
mamba create -n phables -c conda-forge -c anaconda -c bioconda phables
mamba activate phables
mamba install -c gurobi gurobi
phables --help
phables install
phables test

[Mon Jan 22 13:16:08 2024]
Finished job 1.
1 of 2 steps (50%) done
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_phages.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/all_phage_like_edges.fasta.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/unresolved_phage_like_edges.fasta.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/component_phrogs.txt.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/results_MFD.txt.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/results_MFD_details.txt.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/phables_output.log.
Select jobs to execute...
Execute 1 jobs...

[Mon Jan 22 13:16:08 2024]
localrule all:
    input: /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_paths.fasta, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_genome_info.txt, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_edges.fasta, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_component_info.txt, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/phage_like_edges.fasta
    jobid: 0
    reason: Input files updated by another job: /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_paths.fasta, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/phage_like_edges.fasta, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_component_info.txt, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_genome_info.txt, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_edges.fasta
    resources: tmpdir=/tmp

[Mon Jan 22 13:16:08 2024]
Finished job 0.
2 of 2 steps (100%) done
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_paths.fasta.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/phage_like_edges.fasta.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_component_info.txt.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_genome_info.txt.
Removing temporary output /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/test_data/resolved_edges.fasta.
Complete log: .snakemake/log/2024-01-22T131556.789067.snakemake.log


Phables test run was successful!
```
```
phables run --input GFABenchmark/p7_d1_C2.gfa --reads Reads/p7_d1_C2 --threads 32 --output Benchmark/Phables/p7_d1_C2

Activating conda environment: ../../miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/917334462ee3472ccd91f82c51a82e7b_
Output files will be saved to directory, Benchmark/Phables/p7_d1_C2

Activating conda environment: ../../miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/917334462ee3472ccd91f82c51a82e7b_
[Mon Jan 22 13:20:40 2024]
Finished job 3.
1 of 11 steps (9%) done
2024-01-22 13:20:41,638 - INFO - Obtaining edge sequences
2024-01-22 13:20:41,748 - INFO - Writing edge sequences to FASTA file
2024-01-22 13:20:41,935 - INFO - The FASTA file with unitig sequences can be found at Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta
2024-01-22 13:20:41,936 - INFO - Thank you for using gfa2fasta!
[Mon Jan 22 13:20:42 2024]
Finished job 1.
2 of 11 steps (18%) done
Select jobs to execute...
Execute 3 jobs...

[Mon Jan 22 13:20:42 2024]
localrule koverage:
    input: Benchmark/Phables/p7_d1_C2/preprocess/phables.samples.tsv, Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta
    output: Benchmark/Phables/p7_d1_C2/preprocess/temp/ERR12027378.bam, Benchmark/Phables/p7_d1_C2/preprocess/temp/ERR12027378.bam.bai, Benchmark/Phables/p7_d1_C2/preprocess/results/sample_coverm_coverage.tsv
    jobid: 2
    reason: Missing output files: Benchmark/Phables/p7_d1_C2/preprocess/temp/ERR12027378.bam.bai, Benchmark/Phables/p7_d1_C2/preprocess/temp/ERR12027378.bam, Benchmark/Phables/p7_d1_C2/preprocess/results/sample_coverm_coverage.tsv; Input files updated by another job: Benchmark/Phables/p7_d1_C2/preprocess/phables.samples.tsv, Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta
    threads: 8
    resources: tmpdir=/tmp, mem_mb=16000, mem_mib=15259, mem=16000MB


        koverage run coverm             --reads Benchmark/Phables/p7_d1_C2/preprocess/phables.samples.tsv             --ref Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta             --threads 8             --output Benchmark/Phables/p7_d1_C2/preprocess

Activating conda environment: ../../miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/5aa6811b0a74187cc72869c1f738b61c_

[Mon Jan 22 13:20:42 2024]
localrule scan_smg:
    input: Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/../../databases/marker.hmm
    output: Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta.hmmout
    log: Benchmark/Phables/p7_d1_C2/logs/smg_scan_frag_out.log, Benchmark/Phables/p7_d1_C2/logs/smg_scan_frag_err.log, Benchmark/Phables/p7_d1_C2/logs/smg_scan_hmm_out.log, Benchmark/Phables/p7_d1_C2/logs/smg_scan_hmm_err.log
    jobid: 5
    reason: Missing output files: Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta.hmmout; Input files updated by another job: Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta
    threads: 8
    resources: tmpdir=/tmp, mem_mb=16000, mem_mib=15259, mem=16000MB


            run_FragGeneScan.pl -genome=Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta -out=Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta.frag -complete=0 -train=complete -thread=8 1>Benchmark/Phables/p7_d1_C2/logs/smg_scan_frag_out.log 2>Benchmark/Phables/p7_d1_C2/logs/smg_scan_frag_err.log
            hmmsearch --domtblout Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta.hmmout --cut_tc --cpu 8 /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/../../databases/marker.hmm Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta.frag.faa 1>Benchmark/Phables/p7_d1_C2/logs/smg_scan_hmm_out.log 2> Benchmark/Phables/p7_d1_C2/logs/smg_scan_hmm_err.log

Activating conda environment: ../../miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/d37ea6d633b55693c73158c6500b1adb_

[Mon Jan 22 13:20:42 2024]
localrule scan_phrogs:
    input: Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta, /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/../../databases/phrogs_mmseqs_db/phrogs_profile_db
    output: Benchmark/Phables/p7_d1_C2/preprocess/phrogs_annotations.tsv
    log: Benchmark/Phables/p7_d1_C2/logs/phrogs_scan.log
    jobid: 6
    reason: Missing output files: Benchmark/Phables/p7_d1_C2/preprocess/phrogs_annotations.tsv; Input files updated by another job: Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta
    threads: 8
    resources: tmpdir=/tmp, mem_mb=16000, mem_mib=15259, mem=16000MB


        mkdir -p Benchmark/Phables/p7_d1_C2/preprocess/phrogs
        mmseqs createdb Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/../../databases/phrogs_mmseqs_db/phrogs_profile_db Benchmark/Phables/p7_d1_C2/preprocess/phrogs/target_seq > Benchmark/Phables/p7_d1_C2/logs/phrogs_scan.log
        mmseqs search Benchmark/Phables/p7_d1_C2/preprocess/phrogs/target_seq /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/../../databases/phrogs_mmseqs_db/phrogs_profile_db Benchmark/Phables/p7_d1_C2/preprocess/phrogs/results_mmseqs Benchmark/Phables/p7_d1_C2/preprocess/phrogs/tmp --threads 8 -s 7 > Benchmark/Phables/p7_d1_C2/logs/phrogs_scan.log
        mmseqs createtsv Benchmark/Phables/p7_d1_C2/preprocess/phrogs/target_seq /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/../../databases/phrogs_mmseqs_db/phrogs_profile_db Benchmark/Phables/p7_d1_C2/preprocess/phrogs/results_mmseqs Benchmark/Phables/p7_d1_C2/preprocess/phrogs_annotations.tsv --threads 8 --full-header > Benchmark/Phables/p7_d1_C2/logs/phrogs_scan.log
        rm -rf Benchmark/Phables/p7_d1_C2/preprocess/phrogs

Activating conda environment: ../../miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/32796c424418c3481a66d67dc62b1507_

██╗  ██╗ ██████╗ ██╗   ██╗███████╗██████╗  █████╗  ██████╗ ███████╗
██║ ██╔╝██╔═══██╗██║   ██║██╔════╝██╔══██╗██╔══██╗██╔════╝ ██╔════╝
█████╔╝ ██║   ██║██║   ██║█████╗  ██████╔╝███████║██║  ███╗█████╗
██╔═██╗ ██║   ██║╚██╗ ██╔╝██╔══╝  ██╔══██╗██╔══██║██║   ██║██╔══╝
██║  ██╗╚██████╔╝ ╚████╔╝ ███████╗██║  ██║██║  ██║╚██████╔╝███████╗
╚═╝  ╚═╝ ╚═════╝   ╚═══╝  ╚══════╝╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝

[2024:01:22 13:20:42] Copying system default config to Benchmark/Phables/p7_d1_C2/preprocess/koverage.config.yaml
[2024:01:22 13:20:42] Updating config file with new values
[2024:01:22 13:20:42] Writing config file to Benchmark/Phables/p7_d1_C2/preprocess/koverage.config.yaml
[2024:01:22 13:20:42] ------------------
[2024:01:22 13:20:42] | Runtime config |
[2024:01:22 13:20:42] ------------------

koverage:
  args:
    bin_width: 100
    conda_prefix: /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/5aa6811b0a74187cc72869c1f738b61c_/lib/python3.11/site-packages/koverage/workflow/conda
    configfile: Benchmark/Phables/p7_d1_C2/preprocess/koverage.config.yaml
    kmer_max: 5000
    kmer_min: 50
    kmer_sample: 100
    kmer_size: 25
    log: Benchmark/Phables/p7_d1_C2/preprocess/koverage.log
    minimap: sr
    output: Benchmark/Phables/p7_d1_C2/preprocess
    pafs: false
    pyspy: false
    reads: Benchmark/Phables/p7_d1_C2/preprocess/phables.samples.tsv
    ref: Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta
    report: true
    report_max_ctg: 1000
    snake_args:
    - coverm
    snake_default:
    - --rerun-incomplete
    - --printshellcmds
    - --nolock
    - --show-failed-logs
    threads: 8
    use_conda: true
  params:
    coverm: -m count -m rpkm -m tpm -m mean -m covered_fraction -m variance
    jellyfish: -C -s 1G -c 2 --out-counter-len=2 -L 2
resources:
  med:
    cpu: 4
    mem: 16000
    time: 02:00:00
  ram:
    cpu: 2
    mem: 8000
    time: 04:00:00

[2024:01:22 13:20:42] ---------------------
[2024:01:22 13:20:42] | Snakemake command |
[2024:01:22 13:20:42] ---------------------

snakemake -s /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/5aa6811b0a74187cc72869c1f738b61c_/lib/python3.11/site-packages/koverage/workflow/Snakefile --configfile Benchmark/Phables/p7_d1_C2/preprocess/koverage.config.yaml --cores 8 --use-conda --conda-prefix /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/5aa6811b0a74187cc72869c1f738b61c_/lib/python3.11/site-packages/koverage/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs coverm
Config file /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/5aa6811b0a74187cc72869c1f738b61c_/lib/python3.11/site-packages/koverage/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/5aa6811b0a74187cc72869c1f738b61c_/lib/python3.11/site-packages/koverage/workflow/../config/system_config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...
CreateCondaEnvironmentException:
The 'mamba' command is not available in the shell /usr/bin/bash that will be used by Snakemake. You have to ensure that it is in your PATH, e.g., first activating the conda base environment with `conda activate base`.The mamba package manager (https://github.com/mamba-org/mamba) is a fast and robust conda replacement. It is the recommended way of using Snakemake's conda integration. It can be installed with `conda install -n base -c conda-forge mamba`. If you still prefer to use conda, you can enforce that by setting `--conda-frontend conda`.
[2024:01:22 13:20:46] ERROR: Snakemake failed
[Mon Jan 22 13:20:46 2024]
Error in rule koverage:
    jobid: 2
    input: Benchmark/Phables/p7_d1_C2/preprocess/phables.samples.tsv, Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta
    output: Benchmark/Phables/p7_d1_C2/preprocess/temp/ERR12027378.bam, Benchmark/Phables/p7_d1_C2/preprocess/temp/ERR12027378.bam.bai, Benchmark/Phables/p7_d1_C2/preprocess/results/sample_coverm_coverage.tsv
    conda-env: /atlas/matthew.thomas/miniforge3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda/5aa6811b0a74187cc72869c1f738b61c_
    shell:

        koverage run coverm             --reads Benchmark/Phables/p7_d1_C2/preprocess/phables.samples.tsv             --ref Benchmark/Phables/p7_d1_C2/preprocess/edges.fasta             --threads 8             --output Benchmark/Phables/p7_d1_C2/preprocess

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

**Expected behavior**
Phables runs

**Screenshots**

**Desktop (please complete the following information):**

Linux Terminal
Conda version 23.11.0
Mamba version 1.5.5

**Additional context**

**Comment by beardymcjohnface** [comment] 2024-01-23 01:03
The issue is with Snakemake: https://github.com/snakemake/snakemake/pull/2547
We should be able to create an easy workaround; I'll update here when I push a new koverage version.

**Comment by Vini2** [comment] 2024-01-23 08:18
Hi @MJNT1999,

Thanks for your interest in Phables!

Can you remove your existing phables environment, re-set up phables and try again? Please let us know if you still come across this error.

Thanks!

**Comment by Vini2** [comment] 2024-01-23 08:30
Hi @MJNT1999,

Thanks for your interest in Phables!

Can you remove your existing Phables environment using the following command?

```
mamba remove -n phables --all
```

Then, can you re-set up Phables and try again? Please let us know if you still come across this error.

Thanks!

**Comment by MJNT1999** [comment] 2024-01-23 17:58
Hi, thank you so much for the quick response, I've gone ahead and reset up Phables in a fresh Miniforge, again no issues with the install or test

It works with the long reads that I gave it now

However it still fails with the short reads. I reassembled the short reads to check it wasn't my GFA files and get the same result. The assembly was done with shovill using --trim as the only additional option.

```
[Tue Jan 23 12:53:30 2024]
Error in rule faidx_ref:
    jobid: 5
    input: Benchmark/Phables/p7_d1_C2/postprocess/genomes_and_unresolved_edges.fasta
    output: Benchmark/Phables/p7_d1_C2/postprocess/genomes_and_unresolved_edges.fasta.fai
    log: Benchmark/Phables/p7_d1_C2/postprocess/logs/faidx_ref.err (check log file(s) for error details)
    conda-env: /atlas/matthew.thomas/miniforge3/envs/Phables/lib/python3.11/site-packages/phables/workflow/conda/c119b3d9aaeabf4ee35a985fbaa3149b_/lib/python3.11/site-packages/koverage/workflow/conda/7a5a2e79bb8e852e324dc4d63a264a61_
    shell:
        samtools faidx Benchmark/Phables/p7_d1_C2/postprocess/genomes_and_unresolved_edges.fasta 2> Benchmark/Phables/p7_d1_C2/postprocess/logs/faidx_ref.err
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
Logfile Benchmark/Phables/p7_d1_C2/postprocess/logs/faidx_ref.err:
================================================================================
samtools: /atlas/matthew.thomas/miniforge3/envs/Phables/lib/python3.11/site-packages/phables/workflow/conda/c119b3d9aaeabf4ee35a985fbaa3149b_/lib/python3.11/site-packages/koverage/workflow/conda/7a5a2e79bb8e852e324dc4d63a264a61_/bin/../lib/libtinfow.so.6: no version information available (required by samtools)
samtools: /atlas/matthew.thomas/miniforge3/envs/Phables/lib/python3.11/site-packages/phables/workflow/conda/c119b3d9aaeabf4ee35a985fbaa3149b_/lib/python3.11/site-packages/koverage/workflow/conda/7a5a2e79bb8e852e324dc4d63a264a61_/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
samtools: /atlas/matthew.thomas/miniforge3/envs/Phables/lib/python3.11/site-packages/phables/workflow/conda/c119b3d9aaeabf4ee35a985fbaa3149b_/lib/python3.11/site-packages/koverage/workflow/conda/7a5a2e79bb8e852e324dc4d63a264a61_/bin/../lib/libncursesw.so.6: no version information available (required by samtools)
[faidx] Could not build fai index Benchmark/Phables/p7_d1_C2/postprocess/genomes_and_unresolved_edges.fasta.fai

```

**Comment by Vini2** [comment] 2024-01-23 21:56
Hi @MJNT1999,

Can you please check if the file `postprocess/genomes_and_unresolved_edges.fasta` is created?

If that's fine, it looks like a conda issue [samtools/issues/1822](https://github.com/samtools/samtools/issues/1822). 

Can you run the following commands and try setting up Phables again? Sorry for the trouble.

```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict
```

**Comment by MJNT1999** [comment] 2024-01-23 22:00
The file was created, but there is nothing in it

The genomes_and_unresolved_edges.fasta.idx has been created and while it has content it is only 128 kb

Is is the file supposed to be empty? 

I will go ahead with the following commands

**Comment by Vini2** [comment] 2024-01-23 22:41
There should be sequences recorded in `postprocess/genomes_and_unresolved_edges.fasta` if phage sequences were identified.

Can you check if there are any sequences recorded in `phables/resolved_paths.fasta` and  `phables/unresolved_phage_like_edges.fasta`?

**Comment by MJNT1999** [comment] 2024-01-24 03:38
Nothing in the either of those files sadly. I have run GeNomad and Vibrant on this sample and found at least one prophage in this sample.

**Comment by Vini2** [comment] 2024-01-24 06:41
Unfortunately, as mentioned in the [manuscript](https://doi.org/10.1093/bioinformatics/btad586), Phables will not identify prophages as it requires resolving the bacterial component they connect to. Phables will only identify phages that are not integrated into bacterial genomes.

**Comment by MJNT1999** [comment] 2024-01-24 16:18
Ah okay I can't guarentee my prophage is active, thank you so much for your help with this!

**Comment by Vini2** [comment] 2024-01-25 05:08
No problem. I will fix Phables to stop if no genomes are resolved (so it won't run the post-processing steps).

**Comment by RevathyIcosahedron** [comment] 2024-02-01 11:59
I face the similar issue as MJNT1999 above. My test run is fine. Nevertheless, when I give the actual data to the pipeline, Snakemake fails. I should admit that I am quite new to this bioinformatics world. 


snakemake -s /home/ubuntu/miniconda3/envs/phables/lib/python3.11/site-packages/phables/workflow/test_phables.smk --configfile phables.out/config.yaml --cores 1 --use-conda --conda-prefix /home/ubuntu/miniconda3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs
[2024:01:30 19:35:17] Snakemake finished successfully
[2024:01:30 21:27:01] Config file phables.out/config.yaml already exists. Using existing config file.
[2024:01:30 21:27:01] Updating config file with new values
[2024:01:30 21:27:01] Writing config file to phables.out/config.yaml
[2024:01:30 21:27:01] ------------------
[2024:01:30 21:27:01] | Runtime config |
[2024:01:30 21:27:01] ------------------

alpha: 1.2
compcount: 200
conda_prefix: /home/ubuntu/miniconda3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda
configfile: phables.out/config.yaml
covtol: 100
databases: null
dir: /home/ubuntu/miniconda3/envs/phables/lib/python3.11/site-packages/phables/test_data
evalue: 1.0e-10
input: /home/ubuntu/phables/E002.final_k149.gfa
log: phables.out/phables.log
longreads: false
maxpaths: 10
mgfrac: 0.2
mincov: 10
minlength: 2000
output: phables.out
profile: null
reads: /home/ubuntu/Revathy/Ryan/pearl/viromes/reads/trimmed/E002/
resources:
  jobCPU: 8
  jobMem: 16000
seqidentity: 0.3
snake_args: []
snake_default:
- --rerun-incomplete
- --printshellcmds
- --nolock
- --show-failed-logs
system_config: /home/ubuntu/miniconda3/envs/phables/lib/python3.11/site-packages/phables/config/config.yaml
threads: 16
use_conda: true

[2024:01:30 21:27:01] ---------------------
[2024:01:30 21:27:01] | Snakemake command |
[2024:01:30 21:27:01] ---------------------

snakemake -s /home/ubuntu/miniconda3/envs/phables/lib/python3.11/site-packages/phables/workflow/phables.smk --configfile phables.out/config.yaml --cores 16 --use-conda --conda-prefix /home/ubuntu/miniconda3/envs/phables/lib/python3.11/site-packages/phables/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs
[2024:01:30 21:28:06] ERROR: Snakemake failed

I get the mamba build error at the end saying, 

Could not solve for environment specs
The following package could not be installed
└─ koverage >=0.1.8  is not installable because it requires
   └─ datapane >=0.16.7  but there are no viable options
      ├─ datapane 0.16.7 would require
      │  └─ boltons >=20.0.0,<22.0.0 , which conflicts with any installable versions previously reported;
      └─ datapane 0.17.0 would require
         └─ dominate >=2.7.0,<3.0.0 , which conflicts with any installable versions previously reported.

I would appreciate any help.

**Comment by beardymcjohnface** [comment] 2024-02-01 12:48
Hi Revathi, please don't hesitate to open new issues. As a quick fix, can you check if you're using strict channel priority? Set it to flexible or disabled https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html

Vijini, I suspect the problem is having bioconda listed before conda-forge in the env yaml. I never use strict channel_priority and flexible is now the default for conda so this usually slips through the cracks for me, but it's usually easy enough to address. We could also set up a workflow to test the build environments under strict channel priority; I recently did this for Koverage and Hecatomb.

**Comment by RevathyIcosahedron** [comment] 2024-02-01 14:19
Hi Michael Roach, Thank you for your input. Disabling the strict channel priority helped.  I see that step 4/11 is running. Thank you. Will keep you updated. Regards, 
Revathy

**Comment by Vini2** [comment] 2024-03-15 06:24
Closing this issue. Please re-open if needed.

**Closed as completed by Vini2** 2024-03-15 06:24 UTC
Labels: enhancement, help wanted, question
