### ISSUE TITLE
[BUG] UnicodeDecodeError

### ISSUE THREAD

**Issue by ZarulHanifah** [Vini2/ds-bubbles#52] opened 2024-04-24 03:49 UTC
I got some UnicodeDecodeError; here is the  error message:

```
[2024:04:03 14:59:49] Copying system default config to /fs03/jm41/Zarul/C002_E1_results/viral_predict/phables/config.yaml
[2024:04:03 14:59:49] Updating config file with new values
[2024:04:03 14:59:49] Writing config file to /fs03/jm41/Zarul/C002_E1_results/viral_predict/phables/config.yaml
[2024:04:03 14:59:49] ------------------
[2024:04:03 14:59:49] | Runtime config |
[2024:04:03 14:59:49] ------------------

alpha: 1.2
compcount: 200
conda_prefix: /fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/phables/workflow/conda
configfile: /fs03/jm41/Zarul/C002_E1_results/viral_predict/phables/config.yaml
covtol: 100
databases: null
evalue: 1.0e-10
input: /fs03/jm41/Zarul/C002_E1_results/flye/assembly_graph.gfa
log: /fs03/jm41/Zarul/C002_E1_results/viral_predict/phables/phables.log
longreads: true
maxpaths: 10
mgfrac: 0.2
mincov: 10
minlength: 2000
output: /fs03/jm41/Zarul/C002_E1_results/viral_predict/phables
prefix: null
profile: null
reads: /fs03/jm41/Zarul/C002_E1_results/viral_predict/.tmp/tmp_fastq.fastq.gz
resources:
  jobCPU: 8
  jobMem: 16000
seqidentity: 0.3
snake_args: []
snake_default:
- --rerun-incomplete
- --printshellcmds
- --nolock
- --show-failed-logs
system_config: /fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/phables/config/config.yaml
threads: 12
use_conda: true

[2024:04:03 14:59:49] ---------------------
[2024:04:03 14:59:49] | Snakemake command |
[2024:04:03 14:59:49] ---------------------

snakemake -s /fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/phables/workflow/phables.smk --configfile /fs03/jm41/Zarul/C002_E1_results/viral_predict/phables/config.yaml --cores 12 --use-conda --conda-prefix /fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/phables/workflow/conda --rerun-incomplete --printshellcmds --nolock --show-failed-logs
Config file /fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/phables/workflow/../config/config.yaml is extended by additional config specified via the command line.
Config file /fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/phables/workflow/../config/databases.yaml is extended by additional config specified via the command line.
UnicodeDecodeError in file /fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/phables/workflow/rules/02_phables_preflight.smk, line 23:
'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
  File "/fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/phables/workflow/rules/02_phables_preflight.smk", line 23, in <module>
  File "/fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/metasnek/fastq_finder.py", line 196, in parse_samples_to_dictionary
  File "/fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/metasnek/fastq_finder.py", line 140, in parse_samples
  File "/fs03/ie79/Zarul/status_nanopore/C002_E1/.snakemake/conda/9f3dc56d4ec4427ad4b36b73a672b0f6_/lib/python3.11/site-packages/metasnek/fastq_finder.py", line 93, in parse_tsv_file
  File "<frozen codecs>", line 322, in decode
Output files will be saved to directory, /fs03/jm41/Zarul/C002_E1_results/viral_predict/phables

[2024:04:03 15:00:21] ERROR: Snakemake failed
```

Help me please...

**Comment by Vini2** [comment] 2024-04-24 06:11
Hi @ZarulHanifah,

Can you please provide the exact command you used to run Phables?

Thanks!

**Comment by Vini2** [comment] 2024-04-24 06:14
Hi @ZarulHanifah,

Can you please provide the exact command you used to run Phables?

I think the issue is with your path to the reads folder. The `--reads` parameter expects a folder with the reads, not a reads file.

Thanks!

**Comment by Vini2** [comment] 2024-04-24 06:15
Hi @ZarulHanifah,

Can you please provide the exact command you used to run Phables?

Looks like the issue is with your path to the reads folder. The `--reads` parameter expects a folder with the reads, not a reads file.

Thanks!

**Comment by ZarulHanifah** [comment] 2024-04-25 02:10
Yup, that is most likely the case. I gave the file, not the directory..

Thank you :bow:

**Comment by Vini2** [comment] 2024-04-30 05:51
Hope the error is fixed. Closing this issue.

**Closed as completed by Vini2** 2024-04-30 05:51 UTC
